### PR TITLE
[WIP] Created post about illuminate-config.

### PR DESCRIPTION
**Pull request by dimsav**

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
If you finish the conclusion, we can publish this on, let's say, monday?

**Comment by dimsav** [comment]
Sure

**Comment by hannesvdvreken** [comment]
@dimsav any chance on finishing this blog post today or tomorrow?

**Comment by dimsav** [comment]
Yep. I will continue this today

**Comment by dimsav** [comment]
@hannesvdvreken can you please review?

**Comment by hannesvdvreken** [comment]
Looks good. Will merge when you are ready.

**Comment by dimsav** [comment]
@hannesvdvreken fix the date and merge :)

**Comment by hannesvdvreken** [comment]
could you change the date yourself? just rename file and in the header of the file as well.

**Comment by dimsav** [comment]
Done

**Pull request merged**
