### PR TITLE
Added pagination to reduce index site weight

### LINKED ISSUE #26: Pagination
http://jekyllrb.com/docs/pagination/

### PR DESCRIPTION
**Pull request by hannesvdvreken**
### Added

* Pagination, to reduce index site weight

--
fixes #26 

Currently it looks like this (don't mind the font). @arjaneising can style it if he wants, or just merge this in.
screen shot 2015-05-15 at 12 22 53

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
@arjaneising up for this?

**Comment by arjaneising** [comment]
If we are going to do this, I think I really want a nice list of all titles + dates as an archive page somewhere. Shall I add this or are you willing to do so yourself? (I can check the styling of the pagination things too, then.)

**Comment by hannesvdvreken** [comment]
Can't we add a link to https://github.com/madewithlove/blog/tree/gh-pages/_posts as an archive? :D for now we only have 2 pages, so an archive is less urgent than pagination itself.

**Comment by hannesvdvreken** [comment]
@arjaneising ok, I'll create an archive page

**Comment by arjaneising** [comment]
Since the archive page is present now, can this be merged, @hannesvdvreken? (I just added a bit of styling to the links.)

**Comment by hannesvdvreken** [comment]
I'll check it out when I find another power plu

**Pull request merged**
