### PR TITLE
Create code style fixing blog post

### PR DESCRIPTION
**Pull request by hannesvdvreken**
### Added

* Blog post on code style fixing

### CODE REVIEW

**Comment by andreascreten** [comment]
Nice post!

**Comment by hannesvdvreken** [comment]
Thanks!

**Comment by tonysm** [comment]
Really good! :+1:

**Comment by hannesvdvreken** [comment]
Can we publish it?

**Comment by mogetutu** [comment]
Quite insightful especially the line history being lost in code formatting.

**Comment by hannesvdvreken** [comment]
Indeed.

**Pull request merged**
