### PR TITLE
Post/mwl retreat girona

### PR DESCRIPTION
**Pull request by Mangamaui**

### CODE REVIEW

**Comment by Mangamaui** [comment]
Didn't get to see the image that's added in the front matter of the file on localhost. So you might wanna check up on that.

**Comment by hannesvdvreken** [comment]
Would you be ok with publishing this on monday?

**Comment by Mangamaui** [comment]
the rain image should be deleted :)

**Comment by Mangamaui** [comment]
And on Monday is fine by me ^^

**Comment by hannesvdvreken** [comment]
> Didn't get to see the image that's added in the front matter of the file on localhost.

You mean this: https://github.com/madewithlove/blog/blame/post/mwl-retreat-girona/_posts/2015-10-23-mwl-retreat-2015.md#L6 ?

That's for twitter cards and fb to show which picture to use.

**Comment by Mangamaui** [comment]
aha :) 

So what do you think? use that group image somewhere else or leave it as it is?

**Comment by hannesvdvreken** [comment]
As is ;-)

**Comment by hannesvdvreken** [comment]
Ready to just merge on monday!

**Comment by andreascreten** [comment]
Lookin good indeed!

**Pull request merged**
